### PR TITLE
unconditionally declare functions in header + prefix functions + test on ci

### PR DESCRIPTION
**Pull request by madebr**
- Previously, the `tsearch` functions were conditionally declared in the header, depending on cmake.
Remove this conditional and just declare them.
- prefix function: this allows tests to compare this naive tsearch with the upstream glibc implementation in tests that will be coming soon ™️😄 .
- Actually run the *tests* on ci.

### CODE REVIEW

**Comment by madebr** [comment]
> 
> 
> Maybe you are already aware of this, but I should point out that unless you changed something I missed, the `test_tsearch.c` code I wrote never fails -- it was an aid during development, but it does not do any actually useful checking of correctness.
> 
> I might change this someday, but I will not make any promises.

That would be nice, but there is no haste.

Can you also enable the github integration of travis-ci and appveyor for this repo?
It would be nice if a pr is checked before merging.

**Comment by kulp** [comment]
Thanks again !

**Comment by madebr** [comment]
@kulp I'll add support for a testing framework so when we get to writing actual tests, the work will be easy.

Do you have a preference about a unit test framework? Or do you want to try one out?
I don't think we want to invent our own system.

See https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks
There are C++ based ones: **google test, boost test, catch**
Or do we remain with C based ones (`tsearch` is a family of C functions after all): **cunit**

**Comment by kulp** [comment]
@madebr, I agree that writing a testing framework from scratch is not a good idea here. I do not believe the testing framework needs to be in the same language as the source language. For example, I have had good success testing C and C++ code with LuaJIT because of its good FFI layer.

I have used Boost.Test a little bit. If you do not have a strong preference for one or the other, that would be my suggestion.

**Pull request merged**
