### PR TITLE
Fix undefined behavior in `tdelete`

### LINKED ISSUE #9: `tdelete` has undefined behavior
`tdelete` in the current implementation can enter an infinite loop. This bug was [fixed years ago in the tenyr version of `tsearch.c`](https://github.com/kulp/tenyr/commit/3661dff4aff21f5232214d80d2577e18bac79944), but that bugfix was not introduced into [the gist](https://gist.github.com/kulp/3971591) from which [this repository was formed](https://github.com/kulp/naive-tsearch/commit/4b11803851b29362a39c69415841f39dcb478a71). This bug is believed to affect most non-trivial `tsearch` trees that call `tdelete`, although it does not affect any trees that do not call `tdelete`.

The basic difference is the amount of indirection: [the fixed version](https://github.com/kulp/tenyr/blob/86e9f7dce9fc37488dc36486bc34a404f4694d3f/src/tsearch.c#L67-L90) drops a level of pointer indirection that is present in [the broken version](https://github.com/kulp/naive-tsearch/blob/d7bd68191d55c4ff8218c5d3550ac20bbbc9f2e4/tsearch.c.inc#L66-L89).

This time, I noticed this problem manifest as [an indefinite hang in a Travis CI job](https://travis-ci.com/github/kulp/tenyr/jobs/375554224) when I tried to [switch over to naive-tsearch](https://github.com/kulp/tenyr/commit/4acee918fb1373156986ea93d915ba91a4ba286e). The symptom is that `tdelete` gets stuck in [a `while` loop that never exits](https://github.com/kulp/naive-tsearch/blob/d7bd68191d55c4ff8218c5d3550ac20bbbc9f2e4/tsearch.c.inc#L81-L84).

I am pretty confident in the quality of the fix, since it has been present in the `tenyr` code for four years and has been tested by CI on Travis often during that time, but I want to create a testcase for the `naive-tsearch` repository before I merge the fix to this repository.

I plan to create a pull request soon. It will be important to do a release soon after that.

### PR DESCRIPTION
**Pull request by kulp**
Fixes #9.

- [x] The code has been fixed in the PR
- [x] A testcase that would have triggered the bug been added to the PR
- [x] The bug has been fully explained
- [x] The code has been commented

### CODE REVIEW

**Comment by kulp** [comment]
@madebr, I started following your checklist, but I cannot get Conan set up right now on my mac. I did `brew install conan` and it was successful, but these commands did not work, and I have to do other things for a while.
```bash
$ python -m conans.main
/usr/local/opt/python@2/bin/python2.7: No module named conans
$ PYTHONPATH=/usr/local/Cellar/conan/1.28.1/libexec/lib/python3.8/site-packages python3 -m conans.main
/usr/local/opt/python@3.8/bin/python3.8: No module named conans.main
```

I [pushed some changes](https://github.com/kulp/naive-tsearch/compare/46a76f089b5d7d70a76d05744c65ff397ae03692..3c48fe48d17aa53b56d770507e0a371b7c580e2d) but I did not make a tag. If you want to do the Conan testing part and create a `v0.1.1` tag, you can do so.

**Comment by madebr** [comment]
@kulp 
Ok, I'll take over the release.
Can you try replacing `python -m conans.main` with `conan`?
I assumed that conan is installed using pip (python's package manager): `python -m pip install --user conan`.

**Comment by kulp** [comment]
@madebr, using `conan` worked and I was able to successfully build tarballs and test them.

I think I found a small error in the checklist. It should have `cmake --build .` instead of `cmake --build ..` -- otherwise I get `Error: could not load cache` when I test the tarballs in a new directory. I almost did not notice that the first build failed because so much output scrolled past on the screen from the subsequent conan build.

I did not really follow your checklist order properly. Sorry to mess it up a bit. It will probably be better if you finish making the 0.1.1 release whenever you feel like doing it (no rush). Thanks a lot.

**Comment by madebr** [comment]
You're correct. It should be `cmake --build .`.
First fix for the post-release :-)
While doing the first release, I also found it hard to not mess it up.

I will also look at reproducible releases, because running the release generator twice creates different tarballs.
This is probably due to embedded timestamps in the tarballs.

**Comment by madebr** [comment]
I've done the release.

I will open a pr with some fixes to the documentation.
btw, the conan command was wrong.
It should have been `python -m conans.conan`, like we are using on ci.
I will open a pr with the changes.

**Pull request merged**
